# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-damageproto
Summary:    X.Org X11 Protocol damageproto
Version:    1.2.1
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/damageproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-damageproto.yaml
Provides:   damageproto


%description
X.Org X11 Protocol damageproto head files.



%prep
%setup -q -n damageproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_includedir}/X11/extensions/damageproto.h
%{_includedir}/X11/extensions/damagewire.h
%{_datadir}/pkgconfig/damageproto.pc
%doc %{_datadir}/doc/damageproto
# << files


